### ISSUE TITLE
Weird pseudobulk result with fractions after thresholding

### ISSUE THREAD

**Issue by jonathan-columbiau** [bnprks/BPCells#173] opened 2024-12-20 19:32 UTC
Hi, thanks for creating the BPCells package! I found a weird result that I think is a bug while performing an analysis where I am trying to get the fraction of cells per group that express each gene above a certain CPM threshold, while using the pseudobulk_matrix function. Ex: the max value for one of the columns is 4.645053e+296, when it should be between 0 and 1.

Here's some code that replicates the error using some of the code in the introductory vignette: 

library(BPCells)
suppressPackageStartupMessages({
    library(dplyr)
})

data_dir <- file.path(tempdir(), "pbmc-3k")
dir.create(data_dir, recursive = TRUE, showWarnings = FALSE)
setwd(data_dir)

if (!file.exists("pbmc_3k_rna_raw")) {
    mat_raw <- open_matrix_10x_hdf5("pbmc_3k_10x.h5", feature_type="Gene Expression") %>% 
        write_matrix_dir("pbmc_3k_rna_raw")
} else {
    mat_raw <- open_matrix_dir("pbmc_3k_rna_raw")
}
keeper_cells <- colnames(mat_raw)[Matrix::colSums(mat_raw) > 1e3]

keeper_genes <- Matrix::rowSums(mat_raw) > 3
mat <- mat_raw[keeper_genes,keeper_cells]

mat <- multiply_cols(mat, 1/Matrix::colSums(mat) * 1e6)

mat_greater_3_cpm = mat > 3

#pseudobulk by mean to get fraction of genes greater 3 cpm 

groups = c(rep("A",1000),rep("B",1000),rep("C",724)) %>% as.factor()

temp_mat = write_matrix_dir(mat_greater_3_cpm,dir = tempfile("mat2"))
fraction_cells_per_gene_greater_3_cpm = pseudobulk_matrix(temp_mat,groups, method = "mean")

**Comment by bnprks** [comment] 2024-12-20 22:54
Hi @jonathan-columbiau, thanks for the bug report with the reproducible example! This is a type confusion bug in `pseudobulk_matrix` where we forgot to convert all input matrices to `"double"` type, resulting in errors when an integer matrix (like those from `mat > 3`) is produced.

I've opened up a PR to fix this, so your options are:
1. Just run `convert_matrix_type(temp_mat, "double")` before calling `pseudobulk_matrix` as a temporary workaround
2. Re-install from the fixed branch `remotes::install_github("bnprks/BPCells/r", ref="bp/173-fix")`
3. Wait for the PR to be reviewed and merged into the BPCells main branch, then just run `remotes::install("bnprks/BPCells/r")`

One other small tip: you shouldn't need to create your `temp_mat` in this scenario. Since `pseudobulk_matrix` just does a single pass over the input matrix there isn't any real performance benefit of saving to disk.

Hope that helps! Thanks again for the bug report and I'll try to get the fix back into the main branch ASAP

-Ben

**Comment by jonathan-columbiau** [comment] 2024-12-20 23:40
Sounds good! Thanks for the prompt response + help!

**Comment by bnprks** [comment] 2024-12-22 07:11
These fixes are merged into main now, so I think that should resolve this problem. Please comment and @ me so I can re-open if there's still some issue

**Closed by bnprks** 2024-12-22 07:11 UTC
